name: Release native version

on:
  push:
    tags:
    - 'v*'

  workflow_dispatch:

jobs:
  create-gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release 
        # as electron-builder needs draft to upload artifacts, create a draft first
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          draft: true

  release-electron:
    needs: create-gh-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          
      - name: Install libs on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt install -y libusb-1.0-0-dev libudev-dev
      
      - name: Install Dependencies
        run: npm ci

      - name: Build and Release
        run: npx quasar build -m electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }} 
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }} 

  release-electron-macos:
    needs: create-gh-release
    runs-on: self_mac_11.0

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: nvm use v14 && npm ci

      - name: Setup macOS Notarization env
        run: |
          rm -fr ~/private_keys && mkdir ~/private_keys
          echo $APPLE_AUTH_PRIVATE_KEY | base64 -D > ~/private_keys/AuthKey_${APPLE_API_KEY}.p8
        env:
          APPLE_AUTH_PRIVATE_KEY: ${{secrets.APPLE_AUTH_PRIVATE_KEY}}
          APPLE_API_KEY: ${{secrets.APPLE_API_KEY}}

      - name: Build and Release
        run: npx quasar build -m electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }} 
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }} 
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }} 
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}

  release-android:
    needs: create-gh-release
    runs-on: self_mac_11.0
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: nvm use v14 && npm ci

      - name: Build
        run: npx quasar build -m android
        
      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        id: sign_app
        with:
          releaseDirectory: dist/cordova/android/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Set up variable
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          
      - name: Rename file
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} dist/cordova/android/apk/release/Sync2-android-${{ steps.vars.outputs.tag }}.apk

      - name: Calculate checksum of output file
        run: shasum -a 512 dist/cordova/android/apk/release/Sync2-android-${{ steps.vars.outputs.tag }}.apk | cut -f1 -d\ | xxd -r -p | base64 -b 0 > dist/cordova/android/apk/release/Sync2-android-${{ steps.vars.outputs.tag }}-apk-SHASUM

      - name: Upload released files
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/cordova/android/apk/release/Sync2-android-${{ steps.vars.outputs.tag }}.apk
            dist/cordova/android/apk/release/Sync2-android-${{ steps.vars.outputs.tag }}-apk-SHASUM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
